name: Create Tag an Release

on:
  push:
    branches:
      - main
    paths:
      - 'custom_components/aeha_climate/manifest.json'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from JSON
        id: get_version
        run: |
          VERSION=$(jq -r '.version' custom_components/aeha_climate/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ "$VERSION" =~ [a-zA-Z] ]]; then
            echo "IS_PRE_RELEASE=true" >> $GITHUB_ENV
            echo "Modo detectado: Pre-release (Beta)"
          else
            echo "IS_PRE_RELEASE=false" >> $GITHUB_ENV
            echo "Modo detectado: Versi√≥n Estable"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          prerelease: ${{ env.IS_PRE_RELEASE }}
          generate_release_notes: true
          fail_on_unmatched_files: false 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}